---

- import_tasks: secret.yml
  tags: secret
  static: True

- import_tasks: duplicity.yml
  tags: install
  static: True

- import_tasks: backupninja.yml
  tags: ninja
  static: True

- import_tasks: patch.yml
  tags: patch
  static: True

- import_tasks: conf.yml
  tags: conf
  static: True

- import_tasks: duply.yml
  tags: duply
  static: True
