---

- name: verify ansible version
  vars: { version: '2.5' }
  assert:
    quiet: True
    that: ansible_version.full is version_compare(version, '>=')
    msg: Use ansible version {{ version }} at least

- import_tasks: secret.yml
  tags: secret

- import_tasks: duplicity.yml
  tags: install

- import_tasks: backupninja.yml
  tags: ninja

- import_tasks: patch.yml
  tags: patch

- import_tasks: conf.yml
  tags: conf

- import_tasks: duply.yml
  tags: duply
