---

- set_fact: { use_commit: True }


- import_tasks: commit-etc.yml
  vars: { comment: '{{ "Before installing " + list | join(" ") }}' }


- name: install packages

  register: apt

  apt:
    name: '{{ list }}'
    state: latest
    update_cache: True
    cache_valid_time: 300


- import_tasks: commit-etc.yml
  when: apt.changed
  vars: { comment: '{{ "After installing " + list | join(" ") }}' }

